insert into animal_types (id, name_ru, name_en, icon)
values (1, 'Собаки', 'Dogs', '🐕'),
       (2, 'Кошки', 'Cats', '🐈'),
       (3, 'Грызуны', 'Rodents', '🐹'),
       (4, 'Птицы', 'Birds', '🦜')
;

insert into grooming_services (id, name_ru, name_en, price, duration, category, description_en, description_ru, photo_name, is_popular)
values (1,
        'Стрижка когтей кошкам',
        'Nail cutting for cats',
        700,
        45,
        'GROOMING',
        'Claw shearing, claw working',
        'Стрижка когтей, обработка когтя',
        '1.jpg',
        true),

       (2,
        'Стрижка когтей собакам',
        'Nail cutting for dogs',
        900,
        60,
        'GROOMING',
        'Claw shearing, claw working',
        'Стрижка когтей, обработка когтя',
        '2.jpg',
        true),

       (3,
        'Стрижка когтей+ для кошек',
        'Nail cutting+ for cats',
        1500,
        90,
        'GROOMING',
        'Claw shearing, claw treatment, covering, paw massage',
        'Стрижка когтей, обработка когтя, покрытие, массаж лап',
        '3.jpg',
        false),

       (4,
        'Стрижка когтей+ для собак',
        'Nail cutting+ for dogs',
        1800,
        90,
        'GROOMING',
        'Claw shearing, claw treatment, covering, paw massage',
        'Стрижка когтей, обработка когтя, покрытие, массаж лап',
        '4.jpg',
        false),

       (5,
        'Стрижка шерсти для кошки',
        'Haircut for cats',
        2500,
        120,
        'GROOMING',
        'Combing, shearing, styling',
        'Вычесывание, стрижка шерсти, укладка',
        '5.jpg',
        true),

       (6,
        'Стрижка шерсти для собак',
        'Haircut for dogs',
        2500,
        120,
        'GROOMING',
        'Combing, shearing, styling',
        'Вычесывание, стрижка шерсти, укладка',
        '6.jpg',
        true),

       (7,
        'Чистка клетки',
        'Cage cleaning',
        800,
        40,
        'HEALTH',
        'Cleaning the old filler, washing the cage and all its contents, drying',
        'Уборка старого наполнителя, мойка клетки и всего ее содержимого, сушка',
        '7.jpg',
        false),

       (8,
        'Чистка зубов',
        'Tooth brushing',
        800,
        40,
        'HEALTH',
        'Safe plaque removal for pets',
        'Безопасное удаление зубного налета',
        '8.jpg',
        true),

       (9,
        'Ароматерапия и расслабляющий массаж',
        'Aromatherapy & Relaxing Massage',
        4000,
        90,
        'SPA',
        'Stress relief, improved circulation, soothing essential oils',
        'Снятие стресса, улучшение кровообращения, успокаивающие эфирные масла',
        '9.jpg',
        true),

       (10,
        'Песочная ванна и очистка шубки',
        'Sand Bath & Coat Cleansing for Hamsters',
        1500,
        50,
        'SPA',
        'Cleaning wool, removing sebum, preventing skin diseases.',
        'Очистка шерсти, удаление кожного сала, профилактика кожных заболеваний',
        '10.jpg',
        false)
;

insert into service_animal_types (service_id, animal_type_id)
values (1, 2),
       (2, 1),
       (3, 2),
       (4, 1),
       (5, 2),
       (6, 1),
       (7, 3),
       (7, 4),
       (8, 2),
       (8, 1),
       (9, 2),
       (9, 1),
       (10, 3)
;
