insert into masters (en_full_name, en_experience, ru_experience, ru_full_name,  photo_name)
values ('Elena Sokolova',
        'Over 15 years of experience working with animals.  Trained at the European Grooming School. Works with Norwiche terriers, Yorkies, and Spitz. Holds a degree in zoopsychology.',
        'Более 15 лет работы с животными. Прошла обучение в Европейской школе груминга. Работает с норкой, йорками, шпицами. Имеет диплом зоопсихолога.',
        'Елена Владимировна Соколова',
        '1.jpg'),

       ('Anna Morozova',
        '4 years of experience. Started as a grooming assistant, then completed advanced training courses. Specializes in poodle and Bolognese haircuts. Participant in city grooming competitions 2023-2024.',
        'Опыт работы 4 года. Начинала как помощник грумера, затем прошла курсы повышения квалификации. Специализируется на стрижке пуделей и болонок. Участница городских конкурсов груминга 2023-2024.',
        'Анна Сергеевна Морозова',
        '2.jpg'),

       ('Maxim Novikov',
        '8 years working exclusively with cats. Know the specifics of hygienic care for different breeds: Sphynx, Maine Coons, British, Scottish. Provide gentle nail trimming and ear cleaning.',
        '8 лет работаю исключительно с кошками. Знаю особенности гигиенического ухода за разными породами: сфинксы, мейн-куны, британцы, шотландцы. Провожу бережную стрижку когтей и чистку ушей.',
        'Максим Андреевич Новиков',
        '3.jpg'),

       ('Dmitry Vetrov',
        'Veterinary assistant with 10 years of experience, including 5 years in grooming. Can provide first aid, know contraindications for grooming. Work with elderly and sick animals.',
        'Ветеринарный фельдшер с 10-летним стажем, из них 5 лет в груминге. Могу оказать первую помощь, знаю противопоказания для стрижки. Работаю со старыми и больными животными.',
        'Дмитрий Павлович Ветров',
        '4.jpg'),

       ('Olga Lebedeva',
        '12 years in the grooming industry. Work with all breeds of dogs and cats. Quarterly attend master classes from leading groomers in Russia. Use only professional cosmetics.',
        '12 лет в индустрии груминга. Работаю со всеми породами собак и кошек. Ежеквартально прохожу мастер-классы у ведущих грумеров России. Использую только профессиональную косметику.',
        'Ольга Игоревна Лебедева',
        '5.jpg'),

       ('Kristina Pavlova',
        '1.5 years of experience. Graduated from grooming courses with honors. Constantly improving my skills. Work under the supervision of a mentor. Specialize in hygienic haircuts.',
        'Опыт работы 1.5 года. Окончила курсы груминга с отличием. Постоянно повышаю квалификацию. Работаю под присмотром наставника. Специализируюсь на гигиенической стрижке.',
        'Кристина Денисовна Павлова',
        '6.jpg'),

       ('Tatyana Krylova',
        '14 years of experience. Winner of the All-Russian Groomer Competition 2022. Judge of international grooming championships. Author of articles in the professional magazine "Pet Industry". Train young specialists.',
        '14 лет опыта. Победитель Всероссийского конкурса грумеров 2022. Судья международных чемпионатов по грумингу. Автор статей в профессиональном журнале "Пет-индустрия". Обучаю молодых специалистов.',
        'Татьяна Владимировна Крылова',
        '7.jpg'),

       ('Maria Ivanova',
        '5 years of experience in pet SPA procedures. Certified SPA therapist for animals. Specializes in therapeutic baths, aromatherapy wraps, and massage for dogs and cats. Uses natural cosmetics.',
        '5 лет опыта в SPA‑процедурах для животных. Сертифицированный SPA‑терапевт для питомцев. Специализируется на лечебных ваннах, ароматерапевтических обёртываниях и массаже для собак и кошек. Использует натуральную косметику.',
        'Мария Александровна Иванова',
        '8.jpg'),

       ('Igor Petrov',
        '3 years of experience in cage and enclosure cleaning. Certified hygiene specialist. Works with reptiles, rodents, birds, and small mammals. Uses eco‑friendly cleaning agents and disinfectants.',
        '3 года опыта в чистке клеток и вольеров. Сертифицированный специалист по гигиене. Использует экологичные чистящие и дезинфицирующие средства.',
        'Игорь Дмитриевич Петров',
        '9.jpg'),

       ('Anton Lebedev',
        '2 years of experience in SPA and relaxation procedures for pets. Offers warm baths, moisturizing masks, and soothing massages. Specializes in calming anxious animals during procedures.',
        '2 года опыта в SPA и релаксационных процедурах для питомцев. Предлагает тёплые ванны, увлажняющие маски и успокаивающий массаж. Специализируется на работе с тревожными животными во время процедур.',
        'Антон Игоревич Лебедев',
        '10.jpg'),

       ('Denis Smirnov',
        '4 years in animal dental hygiene. Graduated from the Veterinary Dental Assistant Program. Performs teeth brushing, plaque removal, and breath freshening. Educates owners on home dental care.',
        '4 года в гигиене зубов животных. Окончил программу подготовки ассистентов ветеринарного стоматолога. Выполняет чистку зубов, удаление налёта и освежение дыхания. Обучает владельцев уходу за зубами питомца в домашних условиях.',
        'Денис Владимирович Смирнов',
        '11.jpg')
;

insert into masters_services(master_id, service_id)
values (1, 1),
       (1, 2),
       (1, 3),
       (1, 4),
       (1, 5),
       (1, 6),
       (2, 2),
       (2, 4),
       (2, 6),
       (3, 1),
       (3, 3),
       (3, 5),
       (4, 1),
       (4, 2),
       (4, 5),
       (4, 6),
       (5, 1),
       (5, 2),
       (5, 3),
       (5, 4),
       (5, 5),
       (5, 6),
       (6, 5),
       (6, 6),
       (7, 5),
       (7, 6),
       (8, 9),
       (8, 10),
       (9, 7),
       (10, 9),
       (10, 10),
       (11, 8)
;