INSERT INTO quick_questions (rus_question, eng_question, rus_answer, eng_answer, category)
VALUES ('Как часто нужно стричь собаку?',
        'How often should a dog be groomed?',
        'Частота стрижки зависит от породы и типа шерсти. Короткошерстных собак достаточно стричь 1-2 раза в год, длинношерстных — каждые 1-3 месяца. Регулярное вычёсывание помогает поддерживать шерсть в хорошем состоянии между стрижками.',
        'The frequency of grooming depends on the breed and coat type. Short-haired dogs need grooming 1-2 times a year, long-haired dogs — every 1-3 months. Regular brushing helps maintain the coat between grooms.',
        'ABOUT_DOGS'),
       ('Нужно ли стричь собаку под ноль летом?',
        'Should I shave my dog completely in summer?',
        'Нет, это не рекомендуется. Шерсть защищает собаку от перегрева и солнечных ожогов. Лучше сделать гигиеническую стрижку и регулярно вычёсывать подшёрсток.',
        'No, this is not recommended. The coat protects the dog from overheating and sunburn. Better to do a hygienic trim and regularly brush the undercoat.',
        'ABOUT_DOGS'),
       ('Что делать, если собака боится стрижки?',
        'What if my dog is afraid of grooming?',
        'Сообщите мастеру заранее. Мы используем успокаивающие средства, даём перерывы и поощряем лакомствами. Постепенное привыкание и позитивный опыт помогут снизить стресс.',
        'Inform the groomer in advance. We use calming aids, take breaks, and reward with treats. Gradual habituation and positive experience will help reduce stress.',
        'ABOUT_DOGS'),

       ('Стрижёте ли вы кошек?',
        'Do you groom cats?',
        'Да, большинство наших мастеров работают с кошками. Используем безопасную фиксацию, даём перерывы и работаем в спокойной обстановке. Стоимость стрижки кошек от 2500 ₽.',
        'Yes, most of our groomers work with cats. We use safe restraint, take breaks, and work in a calm environment. Cat grooming starts from 2500 ₽.',
        'ABOUT_CATS'),
       ('Как подготовить кошку к грумингу?',
        'How to prepare a cat for grooming?',
        'Коротко подстригите когти за день до визита, приучите к расчёске. Первый раз лучше записаться на короткую гигиеническую стрижку. Возьмите любимые лакомства.',
        'Trim the claws a day before the visit, get used to brushing. For the first time, it''s better to book a short hygienic trim. Bring favorite treats.',
        'ABOUT_CATS'),
       ('Не будет ли кошке стрессово?',
        'Will my cat be stressed?',
        'Мы работаем с феромонами (Feliway), даём кошкам время привыкнуть к обстановке. По возможности не используем фен. Если кошка сильно нервничает, предлагаем седацию после консультации с ветврачом.',
        'We use pheromones (Feliway), give cats time to get used to the environment. We avoid using a hair dryer if possible. If the cat is very nervous, we offer sedation after consultation with a vet.',
        'ABOUT_CATS'),

       ('Сколько стоит стрижка?',
        'How much does grooming cost?',
        'Цена зависит от породы, размера, состояния шерсти и набора услуг. Ориентир: собаки до 5 кг — от 1500 ₽, 5-15 кг — от 2500 ₽, от 15 кг — от 3500 ₽. Кошки — от 2000 ₽. Точную стоимость назовёт мастер после осмотра.',
        'The price depends on breed, size, coat condition and services. Approximate: dogs up to 5 kg — from 1500 ₽, 5-15 kg — from 2500 ₽, over 15 kg — from 3500 ₽. Cats — from 2000 ₽. The exact price will be quoted by the groomer after examination.',
        'PRICES_AND_SERVICES'),
       ('Есть ли скидки для постоянных клиентов?',
        'Are there discounts for regular customers?',
        'Да! Накопительная система: 5% скидка после 3-го визита, 10% после 5-го. Также скидка 10% на день рождения питомца (при предъявлении документов).',
        'Yes! Accumulative system: 5% discount after 3rd visit, 10% after 5th visit. Also 10% discount on pet''s birthday (with proof).',
        'PRICES_AND_SERVICES'),
       ('Что входит в комплексный груминг?',
        'What does comprehensive grooming include?',
        'Мытьё, сушка, вычёсывание, стрижка когтей, чистка ушей, гигиеническая стрижка, модельная стрижка (по желанию). Также доступны дополнительные услуги: SPA-уход, чистка зубов, обработка от паразитов.',
        'Washing, drying, brushing, nail trimming, ear cleaning, hygienic trimming, model haircut (optional). Additional services available: SPA care, teeth cleaning, parasite treatment.',
        'PRICES_AND_SERVICES'),

       ('Как записаться в салон?',
        'How to book an appointment?',
        'Онлайн на нашем сайте через форму записи, по телефону +7 (999) 123-45-67 или через мессенджеры (WhatsApp, Telegram). Мы работаем ежедневно с 10:00 до 20:00.',
        'Online on our website via the booking form, by phone +7 (999) 123-45-67, or via messengers (WhatsApp, Telegram). We work daily from 10:00 to 20:00.',
        'RECORD_AND_TIME'),
       ('Как отменить или перенести запись?',
        'How to cancel or reschedule an appointment?',
        'Сообщите не менее чем за 2 часа. Иначе запись считается неявкой, и может взиматься штраф 500 ₽. Спасибо за понимание!',
        'Notify at least 2 hours in advance. Otherwise, the appointment will be considered a no-show and a 500 ₽ fine may be charged. Thank you for understanding!',
        'RECORD_AND_TIME'),
       ('Сколько длится процедура?',
        'How long does grooming take?',
        'От 1 до 3 часов в зависимости от породы, размера, состояния шерсти и набора услуг. Кошки обычно быстрее — 40-90 минут.',
        'From 1 to 3 hours depending on breed, size, coat condition and services. Cats are usually faster — 40-90 minutes.',
        'RECORD_AND_TIME'),

       ('Как подготовить питомца к первому визиту?',
        'How to prepare a pet for the first visit?',
        'Выгуляйте собаку перед визитом, не кормите за 2-3 часа. Для кошек используйте переноску. Возьмите любимые лакомства и игрушки. Сообщите мастеру о характере питомца.',
        'Walk the dog before the visit, don''t feed for 2-3 hours. For cats, use a carrier. Bring favorite treats and toys. Tell the groomer about your pet''s temperament.',
        'PREPARATION_FOR_VISIT'),
       ('Нужны ли прививки?',
        'Are vaccinations required?',
        'Да, обязательны: от бешенства и комплексная вакцинация (чумка, энтерит и др.). Для щенков до 6 месяцев достаточно 2 прививок. Приносите ветпаспорт!',
        'Yes, mandatory: rabies and comprehensive vaccination (distemper, enteritis, etc.). For puppies under 6 months, 2 vaccinations are sufficient. Bring the veterinary passport!',
        'PREPARATION_FOR_VISIT'),

       ('Когда можно купать питомца после стрижки?',
        'When can I bathe my pet after grooming?',
        'Рекомендуем подождать 3-5 дней, чтобы кожа успокоилась после стрижки. Используйте специальные шампуни для чувствительной кожи.',
        'We recommend waiting 3-5 days for the skin to calm down after grooming. Use special shampoos for sensitive skin.',
        'AFTER_GROOMING_CARE'),
       ('Как часто нужно расчёсывать питомца?',
        'How often should I brush my pet?',
        'Длинношерстных — ежедневно, короткошерстных — 1-2 раза в неделю. Регулярное вычёсывание предотвращает образование колтунов и улучшает состояние кожи.',
        'Long-haired — daily, short-haired — 1-2 times a week. Regular brushing prevents matting and improves skin condition.',
        'AFTER_GROOMING_CARE'),

       ('Можно ли присутствовать при стрижке?',
        'Can I be present during grooming?',
        'Обычно нет — присутствие хозяина может отвлекать питомца. Но вы можете наблюдать через прозрачное окно в зоне ожидания.',
        'Usually no — the owner''s presence can distract the pet. But you can watch through the transparent window in the waiting area.',
        'SALON_RULES'),
       ('Можно ли прийти с детьми?',
        'Can I come with children?',
        'Да, но предупреждаем, что животные могут нервничать. Пожалуйста, объясните детям правила поведения и следите за ними.',
        'Yes, but please note that animals may get nervous. Please explain safety rules to children and supervise them.',
        'SALON_RULES');