server:
  port: 8082
  servlet:
    context-path: /adminapp
spring:
  mail:
    host: smtp.mail.ru
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
  datasource:
    url: jdbc:postgresql://localhost:5432/zoo-info
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    initialization-mode: always
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
      default_batch_fetch_size: 20
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
app:
  email: support@royalfluff.ru
  phone: +7 (911) 765-43-21
  work-hours: 10:00 - 20:00
  master-photo-path: /images/masters
  service-photo-path: /images/services
  employee-photo-path: /images/employees
  admin-email: ${ADMIN_EMAIL}
  mail-printform-path: /mail/
  mail:
    username: ${MAIL_USERNAME}
  max-file-size: 400 KB