insert into animal_types (id, name_ru, name_en, icon)
values (1, 'Собаки', 'Dogs', '🐕'),
       (2, 'Кошки', 'Cats', '🐈'),
       (3, 'Грызуны', 'Rodents', '🐹'),
       (4, 'Птицы', 'Birds', '🦜')
;

insert into grooming_services (id, name_ru, name_en, price, duration, category, description_en, description_ru, photo_name, is_popular)
values (1,
        'Стрижка когтей',
        'Nail cutting',
        500,
        15,
        'GROOMING',
        'Claw shearing, claw working',
        'Стрижка когтей, обработка когтя',
        '1.jpg',
        true),

       (2,
        'Стрижка когтей+',
        'Nail cutting+',
        500,
        15,
        'GROOMING',
        'Claw shearing, claw treatment, covering, paw massage',
        'Стрижка когтей, обработка когтя, покрытие, массаж лап',
        '2.jpg',
        false),

       (3,
        'Стрижка шерсти',
        'Haircut',
        2500,
        60,
        'GROOMING',
        'Combing, shearing, styling',
        'Вычесывание, стрижка шерсти, укладка',
        '3.jpg',
        true),

       (4,
        'Чистка клетки',
        'Cage cleaning',
        800,
        20,
        'HEALTH',
        'Cleaning the old filler, washing the cage and all its contents, drying',
        'Уборка старого наполнителя, мойка клетки и всего ее содержимого, сушка',
        '4.jpg',
        false),

       (5,
        'Чистка зубов',
        'Tooth brushing',
        700,
        40,
        'HEALTH',
        'Safe plaque removal for pets',
        'Безопасное удаление зубного налета',
        '5.jpg',
        true),

       (6,
        'Ароматерапия и расслабляющий массаж',
        'Aromatherapy & Relaxing Massage',
        3000,
        50,
        'SPA',
        'Stress relief, improved circulation, soothing essential oils',
        'Снятие стресса, улучшение кровообращения, успокаивающие эфирные масла',
        '6.jpg',
        true),

       (7,
        'Песочная ванна и очистка шубки',
        'Sand Bath & Coat Cleansing for Hamsters',
        1500,
        50,
        'SPA',
        'Cleaning wool, removing sebum, preventing skin diseases.',
        'Очистка шерсти, удаление кожного сала, профилактика кожных заболеваний',
        '7.jpg',
        false)
;

insert into service_animal_types (service_id, animal_type_id)
values (1, 1),
       (1, 2),
       (2, 1),
       (2, 2),
       (3, 1),
       (3, 2),
       (4, 3),
       (4, 4),
       (5, 1),
       (5, 2),
       (6, 1),
       (6, 2),
       (7, 3)
;
