insert into masters ( en_full_name, en_experience,en_specialisation, ru_experience, ru_full_name, ru_specialisation, photo_name)
values ( 'Elena Sokolova',
         'Over 15 years of experience working with animals.  Trained at the European Grooming School. Works with Norwiche terriers, Yorkies, and Spitz. Holds a degree in zoopsychology.',
        'Grooming cats and small breed dogs.',
        'Более 15 лет работы с животными. Прошла обучение в Европейской школе груминга. Работает с норкой, йорками, шпицами. Имеет диплом зоопсихолога.',
         'Елена Владимировна Соколова',
        'Груминг кошек и собак мелких пород.',
        '1.jpg'),

       ( 'Anna Morozova',
         '4 years of experience. Started as a grooming assistant, then completed advanced training courses. Specializes in poodle and Bolognese haircuts. Participant in city grooming competitions 2023-2024.',
         'Poodle and Bolognese grooming specialist.',
         'Опыт работы 4 года. Начинала как помощник грумера, затем прошла курсы повышения квалификации. Специализируется на стрижке пуделей и болонок. Участница городских конкурсов груминга 2023-2024.',
         'Анна Сергеевна Морозова',
         'Стрижка пуделей и болонок.',
        '2.jpg'),

       ( 'Maxim Novikov',
         '8 years working exclusively with cats. Know the specifics of hygienic care for different breeds: Sphynx, Maine Coons, British, Scottish. Provide gentle nail trimming and ear cleaning.',
         'Feline grooming specialist.',
         '8 лет работаю исключительно с кошками. Знаю особенности гигиенического ухода за разными породами: сфинксы, мейн-куны, британцы, шотландцы. Провожу бережную стрижку когтей и чистку ушей.',
         'Максим Андреевич Новиков',
         'Груминг кошек.',
        '3.jpg'),

       ( 'Dmitry Vetrov',
         'Veterinary assistant with 10 years of experience, including 5 years in grooming. Can provide first aid, know contraindications for grooming. Work with elderly and sick animals.',
         'Veterinary grooming for elderly and sick animals.',
         'Ветеринарный фельдшер с 10-летним стажем, из них 5 лет в груминге. Могу оказать первую помощь, знаю противопоказания для стрижки. Работаю со старыми и больными животными.',
         'Дмитрий Павлович Ветров',
         'Ветеринарный груминг.',
        '4.jpg'),

       ( 'Olga Lebedeva',
         '12 years in the grooming industry. Work with all breeds of dogs and cats. Quarterly attend master classes from leading groomers in Russia. Use only professional cosmetics.',
         'All breeds grooming specialist.',
         '12 лет в индустрии груминга. Работаю со всеми породами собак и кошек. Ежеквартально прохожу мастер-классы у ведущих грумеров России. Использую только профессиональную косметику.',
         'Ольга Игоревна Лебедева',
         'Груминг всех пород.',
        '5.jpg'),

       ( 'Kristina Pavlova',
         '1.5 years of experience. Graduated from grooming courses with honors. Constantly improving my skills. Work under the supervision of a mentor. Specialize in hygienic haircuts.',
         'Hygienic haircuts for beginners.',
         'Опыт работы 1.5 года. Окончила курсы груминга с отличием. Постоянно повышаю квалификацию. Работаю под присмотром наставника. Специализируюсь на гигиенической стрижке.',
         'Кристина Денисовна Павлова',
         'Гигиеническая стрижка.',
        '6.jpg'),

       ( 'Tatyana Krylova',
         '14 years of experience. Winner of the All-Russian Groomer Competition 2022. Judge of international grooming championships. Author of articles in the professional magazine "Pet Industry". Train young specialists.',
         'Competition winner and grooming judge.',
         '14 лет опыта. Победитель Всероссийского конкурса грумеров 2022. Судья международных чемпионатов по грумингу. Автор статей в профессиональном журнале "Пет-индустрия". Обучаю молодых специалистов.',
         'Татьяна Владимировна Крылова',
         'Груминг высшей категории.',
        '7.jpg')
;